version: "3.1"

services:

  db:
    container_name: cartao
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      DB_PORT: 5434
    ports:
      - "5434:5434"