openapi: 3.0.3
info:
  title: vasco-bank-cartao - OpenAPI 3.0
  description: ''
  version: 1.0.11

servers:
  - url: https:/vasco-bank-cartao/api/v1
  
tags:
  - name: cartaoCredito
    description: Operations about user
paths:

  /cartaoCredito/{userId}:
    get:
      tags:
        - cartaoCredito
      summary: Retorna informação do cartao de credito caso se existir
      description: This can only be done by the logged in user.
      operationId: createUser
      parameters:
        - name: userId
          in: path
          description: ID do usuario
          required: true
          schema:
            type: integer
            format: int64
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cartoes'
            application/xml:
              schema:
                $ref: '#/components/schemas/cartoes'
  /cartaoCredito/aquisicao:
    post:
      tags:
        - cartaoCredito
      summary: precisamos verificar antes se ele é elegivel?
      description: Creates list of users with given input array
      operationId: cartaoCreditoAquisicao
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/cartaoCredito'
          application/xml:
            schema:
              $ref: '#/components/schemas/cartaoCredito'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/cartaoCredito'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cartaoCredito'          
            application/xml:
              schema:
                $ref: '#/components/schemas/cartaoCredito'
        default:
          description: successful operation

  /cartaoCredito/{userId}/{cartaoId}/limite:
    get:
      tags:
        - cartaoCredito
      summary: Get limite do cartao
      description: ''
      operationId: cartaoCreditoLimite
      parameters:
        - name: userId
          in: path
          description: ID do usuario
          required: true
          schema:
            type: integer
            format: int64
        - name: cartaoId
          in: path
          description: ID do cartao
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/limite'          
            application/xml:
              schema:
                $ref: '#/components/schemas/limite'
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
          
  /cartaoCredito/{userId}/{cartaoId}/fatura:
    get:
      tags:
        - cartaoCredito
      summary: Get fatura do cartao
      description: ''
      operationId: cartaoCreditoFatura
      parameters:
        - name: userId
          in: path
          description: ID do usuario
          required: true
          schema:
            type: integer
            format: int64
        - name: cartaoId
          in: path
          description: ID do cartao
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fatura'          
            application/xml:
              schema:
                $ref: '#/components/schemas/fatura'
        '400':
          description: Invalid username supplied
        '404':
          description: User not found

  /cartaoCredito/{userId}/{cartaoId}/extrato:
    get:
      tags:
        - cartaoCredito
      summary: Get user by user name
      description: ''
      operationId: cartaoCreditoExtrato
      parameters:
        - name: userId
          in: path
          description: ID do usuario
          required: true
          schema:
            type: integer
            format: int64
        - name: cartaoId
          in: path
          description: ID do cartao
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/extrato'          
            application/xml:
              schema:
                $ref: '#/components/schemas/extrato'
        '400':
          description: Invalid username supplied
        '404':
          description: User not found     
          
  /cartaoCredito/pagamento:
    post:
      tags:
        - cartaoCredito
      summary: Get user by user name
      description: ''
      operationId: cartaoCreditoPagamento
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/cartaoCredito'
          application/xml:
            schema:
              $ref: '#/components/schemas/cartaoCredito'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/cartaoCredito'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cartaoCredito'          
            application/xml:
              schema:
                $ref: '#/components/schemas/cartaoCredito'
        '400':
          description: Invalid username supplied
        '404':
          description: User not found   
    
components:
  schemas:
    cartoes:
          type: array
          xml:
            wrapped: true
            name: cartoes
          items:
            $ref: '#/components/schemas/cartaoCredito'
         
    cartaoCredito:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        nome:
          type: string
          example: 'John K. pascal'
        numero:
          type: string
          example: '1234 1232 1234 1232'
        dataVencimento:
          type: string
          format: date
        cvv:
          type: string
          example: '123'
        limite:
          type: number
          example: 9.999
        eligivelAumentoLimite:
          type: boolean
          example: 'false'
        virtual:
          type: boolean
          example: 'false'
      xml:
        name: cartaoCredito
    limite:
        type: object
        properties:
          valor:
            type: number
            format: int64
            example: 99.999
        xml:
          name: limite
    fatura:
        type: object
        properties:
          id:
            type: integer
            format: int64
            example: 10
          valorTotal:
            type: number
            format: int64
            example: 99.999
          paga:
            type: boolean
            example: false
          dataVencimento:
            type: string
            format: date
          compras:
            type: array
            xml:
              wrapped: true
              name: compra
            items:
              $ref: '#/components/schemas/compra'
        xml:
          name: fatura
          
    compra:
        type: object
        properties:
          id:
            type: integer
            format: int64
            example: 10
          valor:
            type: number
            format: int64
            example: 99.999
          dataCompra:
            type: string
            format: date
          local:
            type: string
            example: 'uber'
          parcelas:
            type: integer
            example: 12
        xml:
          name: compra
          
    extrato:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        dataOperacao:
          type: string
          format: date
        operacao:
          type: string
          enum:
            - PIX
            - BOLETO
            - INTRABANCO
            - PAGCARTAO
      xml:
        name: extrato
          
          
           
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://vasco-bank-cartao/api/v1/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
